import { Unit } from "@/d";

export const UnitsArray: Unit[] = [
  {
    name: "Akali",
    cost: 2,
    traits: ["quickstriker", "rebel"],
    imgsrc: "akali.avif",
  },
  {
    name: "Ambessa",
    cost: 4,
    traits: ["conquerer", "emissary", "quickstriker"],
    imgsrc: "ambessa.avif",
  },
  {
    name: "Amumu",
    cost: 1,
    traits: ["automata", "watcher"],
    imgsrc: "amumu.avif",
  },
  {
    name: "Blitzcrank",
    cost: 3,
    traits: ["automata", "dominator"],
    imgsrc: "blitzcrank.avif",
  },
  {
    name: "Caitlyn",
    cost: 5,
    traits: ["enforcer", "sniper"],
    imgsrc: "caitlyn.avif",
  },
  {
    name: "Camille",
    cost: 2,
    traits: ["ambusher", "enforcer"],
    imgsrc: "camille.avif",
  },
  {
    name: "Cassiopeia",
    cost: 3,
    traits: ["black rose", "dominator"],
    imgsrc: "cassiopeia.avif",
  },
  {
    name: "Corki",
    cost: 4,
    traits: ["artillerist", "scrap"],
    imgsrc: "corki.avif",
  },
  {
    name: "Darius",
    cost: 1,
    traits: ["conquerer", "watcher"],
    imgsrc: "darius.avif",
  },
  {
    name: "Draven",
    cost: 1,
    traits: ["conquerer", "pit fighter"],
    imgsrc: "draven.avif",
  },
  {
    name: "Ekko",
    cost: 4,
    traits: ["ambusher", "firelight", "scrap"],
    imgsrc: "ekko.avif",
  },
  {
    name: "Elise",
    cost: 4,
    traits: ["black rose", "bruiser", "form swapper"],
    imgsrc: "elise.avif",
  },
  {
    name: "Ezreal",
    cost: 3,
    traits: ["academy", "artillerist", "rebel"],
    imgsrc: "ezreal.avif",
  },
  {
    name: "Gangplank",
    cost: 3,
    traits: ["form swapper", "pit fighter", "scrap"],
    imgsrc: "gangplank.avif",
  },
  {
    name: "Garen",
    cost: 4,
    traits: ["emissary", "watcher"],
    imgsrc: "garen.avif",
  },
  {
    name: "Heimerdinger",
    cost: 4,
    traits: ["academy", "visionary"],
    imgsrc: "heimerdinger.avif",
  },
  {
    name: "Illaoi",
    cost: 4,
    traits: ["rebel", "sentinel"],
    imgsrc: "illaoi.avif",
  },
  {
    name: "Irelia",
    cost: 1,
    traits: ["rebel", "sentinel"],
    imgsrc: "irelia.avif",
  },
  {
    name: "Jayce",
    cost: 5,
    traits: ["academy", "form swapper"],
    imgsrc: "jayce.avif",
  },
  {
    name: "Jinx",
    cost: 5,
    traits: ["ambusher", "rebel"],
    imgsrc: "jinx.avif",
  },
  {
    name: "Kog'Maw",
    cost: 3,
    traits: ["automata", "sniper"],
    imgsrc: "kogmaw.avif",
  },
  {
    name: "LeBlanc",
    cost: 5,
    traits: ["black rose", "sorcerer"],
    imgsrc: "leblanc.avif",
  },
  {
    name: "Leona",
    cost: 2,
    traits: ["academy", "sentinel"],
    imgsrc: "leona.avif",
  },
  {
    name: "Loris",
    cost: 3,
    traits: ["enforcer", "sentinel"],
    imgsrc: "loris.avif",
  },
  {
    name: "Lux",
    cost: 1,
    traits: ["academy", "sorcerer"],
    imgsrc: "lux.avif",
  },
  {
    name: "Maddie",
    cost: 1,
    traits: ["enforcer", "sniper"],
    imgsrc: "maddie.avif",
  },
  {
    name: "Malzahar",
    cost: 5,
    traits: ["automata", "visionary"],
    imgsrc: "malzahar.avif",
  },
  {
    name: "Mel",
    cost: 6,
    traits: ["banished mage"],
    imgsrc: "mel.avif",
  },
  {
    name: "Mordekaiser",
    cost: 5,
    traits: ["conquerer", "dominator"],
    imgsrc: "mordekaiser.avif",
  },
  {
    name: "Morgana",
    cost: 1,
    traits: ["black rose", "visionary"],
    imgsrc: "morgana.avif",
  },
  {
    name: "Dr. Mundo",
    cost: 4,
    traits: ["dominator", "experiment"],
    imgsrc: "mundo.avif",
  },
  {
    name: "Nami",
    cost: 3,
    traits: ["emissary", "sorcerer"],
    imgsrc: "nami.avif",
  },
  {
    name: "Nocturne",
    cost: 2,
    traits: ["automata", "quickstriker"],
    imgsrc: "nocturne.avif",
  },
  {
    name: "Nunu & Willump",
    cost: 3,
    traits: ["bruiser", "experiment", "visionary"],
    imgsrc: "nunuwillump.avif",
  },
  {
    name: "Powder",
    cost: 1,
    traits: ["ambusher", "family", "scrap"],
    imgsrc: "powder.avif",
  },
  {
    name: "Rell",
    cost: 2,
    traits: ["conquerer", "sentinel", "visionary"],
    imgsrc: "rell.avif",
  },
  {
    name: "Renata Glasc",
    cost: 2,
    traits: ["chem-baron", "visionary"],
    imgsrc: "renataglasc.avif",
  },
  {
    name: "Renni",
    cost: 3,
    traits: ["bruiser", "chem-baron"],
    imgsrc: "renni.avif",
  },
  {
    name: "Rumble",
    cost: 5,
    traits: ["junker king", "scrap", "sentinel"],
    imgsrc: "rumble.avif",
  },
  {
    name: "Scar",
    cost: 3,
    traits: ["firelight", "watcher"],
    imgsrc: "scar.avif",
  },
  {
    name: "Sett",
    cost: 2,
    traits: ["bruiser", "rebel"],
    imgsrc: "sett.avif",
  },
  {
    name: "Sevika",
    cost: 5,
    traits: ["chem-baron", "high roller", "pit fighter"],
    imgsrc: "sevika.avif",
  },
  {
    name: "Silco",
    cost: 4,
    traits: ["chem-baron", "dominator"],
    imgsrc: "silco.avif",
  },
  {
    name: "Singed",
    cost: 1,
    traits: ["chem-baron", "sentinel"],
    imgsrc: "singed.avif",
  },
  {
    name: "Smeech",
    cost: 3,
    traits: ["ambusher", "chem-baron"],
    imgsrc: "smeech.avif",
  },
  {
    name: "Steb",
    cost: 1,
    traits: ["bruiser", "enforcer"],
    imgsrc: "steb.avif",
  },
  {
    name: "Swain",
    cost: 3,
    traits: ["conquerer", "form swapper", "sorcerer"],
    imgsrc: "swain.avif",
  },
  {
    name: "Tristana",
    cost: 2,
    traits: ["artillerist", "emissary"],
    imgsrc: "tristana.avif",
  },
  {
    name: "Trundle",
    cost: 1,
    traits: ["bruiser", "scrap"],
    imgsrc: "trundle.avif",
  },
  {
    name: "Twisted Fate",
    cost: 3,
    traits: ["enforcer", "quickstriker"],
    imgsrc: "twistedfate.avif",
  },
  {
    name: "Twitch",
    cost: 4,
    traits: ["experiment", "sniper"],
    imgsrc: "twitch.avif",
  },
  {
    name: "Urgot",
    cost: 2,
    traits: ["artillerist", "experiment", "pit fighter"],
    imgsrc: "urgot.avif",
  },
  {
    name: "Vander",
    cost: 2,
    traits: ["family", "watcher"],
    imgsrc: "vander.avif",
  },
  {
    name: "Vex",
    cost: 1,
    traits: ["rebel", "visionary"],
    imgsrc: "vex.avif",
  },
  {
    name: "Vi",
    cost: 4,
    traits: ["enforcer", "pit fighter"],
    imgsrc: "vi.avif",
  },
  {
    name: "Viktor",
    cost: 6,
    traits: ["machine herald"],
    imgsrc: "viktor.avif",
  },
  {
    name: "Violet",
    cost: 1,
    traits: ["family", "pit fighter"],
    imgsrc: "violet.avif",
  },
  {
    name: "Vladimir",
    cost: 2,
    traits: ["black rose", "sorcerer", "watcher"],
    imgsrc: "vladimir.avif",
  },
  {
    name: "Warwick",
    cost: 6,
    traits: ["blood hunter", "experiment"],
    imgsrc: "warwick.avif",
  },
  {
    name: "Zeri",
    cost: 2,
    traits: ["firelight", "sniper"],
    imgsrc: "zeri.avif",
  },
  {
    name: "Ziggs",
    cost: 2,
    traits: ["dominator", "scrap"],
    imgsrc: "ziggs.avif",
  },
  {
    name: "Zoe",
    cost: 4,
    traits: ["rebel", "sorcerer"],
    imgsrc: "zoe.avif",
  },
  {
    name: "Zyra",
    cost: 1,
    traits: ["experiment", "sorcerer"],
    imgsrc: "zyra.avif",
  },
];
